config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'groups/index'
  get 'groups/show'
  get 'groups/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search"=>"searches#search", as: "search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update, :follow_users] do
    member do
      get :follow_users, :follower_users
    end
    resource :relationship, only: [:create, :destroy]
  end
  resources :groups do
    get "join" => "groups#join"
    delete "out_of_group" => "groups#out_of_group"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: 'User'
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :group_image

  def is_owned_by?(user)
    owner.id == user.id
  end

  def get_group_image
    (group_image.attached?) ? group_image : "no_image.jpg"
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :ensure_correct_owner, only: [:edit, :update, :destroy]

  def index
    @book = Book.new
    @groups = Group.all
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
    @user = User.find(current_user.id)
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path, method: :post
    else
      render 'new'
    end
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def join #メンバーイン
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to group_path(@group)
  end

  def out_of_group  #メンバーアウト
    @group = Group.find(params[:group_id])
    @group.users.delete(current_user)
    redirect_to group_path(@group)
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    EventMailer.send_mail(@mail_title,@mail_content,@group.users).deliver
  end

  private
  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_owner
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with model:group, local:true do |f| %>
<%= render 'layouts/errors', obj: @group %>
  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :グループ紹介 %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :group_image, class: 'form-control-file', accept: "image/*" %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/groups/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介</th>
      <th>オーナー</th>
      <th>メンバー数</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td>
          <%= link_to(group) do %>
            <%= image_tag group.get_group_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to group.name, group %></td>
        <td><%= group.introduction %></td>
        <td><%= group.owner.name %></td>
        <td><i class="fa-solid fa-users"></i> <%= group.users.count %> 人</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Group</h1>
  		<%= render 'form', group: @group %>
  		<%= link_to 'Show', @group %> |
  		<%= link_to 'Back', groups_path, class: "back" %>
  	</div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <% unless current_user.guest_user? %>
        <%= link_to "グループを作成する", new_group_path, class: "btn btn-sm btn-success my-2" %>
      <% end %>
      <%= render 'index', groups: @groups %>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Create Group</h1>
  		<%= render 'form', group: @group %>
  		<%= link_to 'Back', groups_path, class: "back" %>
  	</div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1><%= @group.name %>メンバーへのメール</h1>
  		<%= form_with url: group_send_mail_path(@group), method: :get, local: true do |f| %>
  		  <div class="form-group">
  		    <%= f.label :title %>
  		    <%= f.text_field :mail_title, class: "form-control" %>
  		  </div>
  		  <div class="form-group">
  		    <%= f.label :content %>
  		    <%= f.text_area :mail_content, class: "form-control" %>
  		  </div>
  		  <div class="form-group">
          <%= f.submit "送信", class: 'btn btn-success' %>
        </div>
  		<% end %>
  		<%= link_to 'Back', group_path(@group), class: "back" %>
  	</div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
    <div class="margin_top">内容は以下の通りです</div>
    <div class="small_margin_top">
      [タイトル]<p class="font-weight-bold"><%= @mail_title %></p>
    </div>
    <div class="small_margin_top">
      [本文]<p class="font-weight-bold"><%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
    </div>
  </div>
  <%= link_to '戻る', group_path(@group) %>
</div>

app/views/groups/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Group detail</h2>
  		<table class='table'>
  		  <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介</th>
            <th>メンバー</th>
          </tr>
        </thead>
        <tbody>
    		  <tr>
            <td><%= image_tag @group.get_group_image, size:"100x100" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |member| %>
                <%= member.name %><br>
              <% end %>
            </td>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to 'Mail', group_new_mail_path(@group), class: "btn btn-sm btn-primary" %></td>
              <td><%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to 'Destroy', @group, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% end %>
            <% if @group.users.include?(current_user) %>
              <td><%= link_to 'Leave this group', group_out_of_group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% else %>
              <td><%= link_to 'Join this group', group_join_path(@group), class: "btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <%= link_to 'グループ一覧に戻る', groups_path %>
    </div>
  </div>
</div>